[package]
name = "gnnuhub-api"
description = "赣南师范大学教务系统 API 客户端"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
authors.workspace = true
repository.workspace = true

[dependencies]
gnnuhub-core.workspace = true
gnnuhub-crypto.workspace = true
gnnuhub-ocr.workspace = true

reqwest.workspace = true
tokio.workspace = true
serde.workspace = true
serde_json.workspace = true
thiserror.workspace = true
tracing.workspace = true
scraper.workspace = true
url.workspace = true

[dev-dependencies]
anyhow.workspace = true
tracing-subscriber.workspace = true
